bpf: Fix missing SO_ATTACH_BPF definition
bpf_common.c:135:37: error: 'SO_ATTACH_BPF' undeclared (first use in this function)

Adding it to bpf_common.h and removing from tests (not used only in bpf_map01.c).
While at it moving also lapi/bpf.h from tests to bpf_common.h.

Signed-off-by: Petr Vorel <pvorel@suse.cz>