Applied patch from David Marlin: I am working with LTP from a current CVS checkout.  I am using Red Hat Enterprise Linux AS release 3 (Taroon Update 5), kernel-2.4.21-32.EL, and gcc-3.2.3.
When building, LTP I receive the following error message:

gcc -Wall -O2 -I../include  -Wall   -c -o tst_kvercmp.o tst_kvercmp.c
tst_kvercmp.c:44:22: macro "strsep" requires 2 arguments, but only 1 given
tst_kvercmp.c: In function `get_kver':
tst_kvercmp.c:44: error: 'strsep' redeclared as different kind of symbol
/usr/include/string.h:310: error: previous declaration of 'strsep' was here
tst_kvercmp.c:44: warning: unused variable `strsep'


In /usr/include/string.h I find:

#ifdef  __USE_BSD
/* Return the next DELIM-delimited token from *STRINGP,
     terminating it with a '\0', and update *STRINGP to point past it.  */
extern char *strsep (char **__restrict __stringp,
                       __const char *__restrict __delim) __THROW;
#endif


In lib/tst_kvercmp.c I find:

      extern char *strsep();          /* shut up some compilers */


 From the CVS log it appears that this was added "to provide
compatibility of LTP with Solaris, HP-UX and AIX".  If not needed for
Linux, it seems we could make this include conditional, i.e.,
!defined(linux).

Attached is a patch I used to work around this error.

Note: this error does not occur if I remove optimization (-O2) from the
CFLAGS.


Thank you,

d.marlin