syscalls/flock: Fix O_CREAT undeclared when building with musl
When building with musl, the following error appears:

|ck01.c:157:22: error: 'O_CREAT' undeclared (first use in this function); did you mean 'S_IREAD'?
|   fd = open(filename, O_CREAT | O_TRUNC | O_RDWR, 0644);
|                       ^~~~~~~
|                       S_IREAD

This is because the 'O_CREAT' defined in fcntl.h, so including it.

Signed-off-by: Dengke Du <dengke.du@windriver.com>
Acked-by: Cyril Hrubis <chrubis@suse.cz>