syscalls: {readlink,mknod,fchown,open,mkdir}at: Fix build.
Including dirent.h (to have DIR defined) in safe_macros.h caused namespace
collision of dirfd() function and dirfd variable in the testcases.

mknodat01.c:53:12: error: ???dirfd??? redeclared as different kind of symbol
 static int dirfd, fd;
            ^
In file included from ../../../../include/safe_macros.h:28:0,
                 from mknodat01.c:38:
/usr/include/dirent.h:223:12: note: previous declaration of ???dirfd??? was here
 extern int dirfd (DIR *__dirp) __THROW __nonnull ((1));
            ^
<builtin>: recipe for target 'mknodat01' failed

Reported-by: Vinson Lee <vlee@twopensource.com>
Signed-off-by: Cyril Hrubis <chrubis@suse.cz>