Remove bogus Aarch64 system call numbers
Aarch64 build fails with:

cacheflush01.c:52:26: fatal error: asm/cachectl.h: No such file or directory
 #include <asm/cachectl.h>

This is caused by bogus definitions of cacheflush and set_tls, which are
private 32bit ARM system calls. These should not be used on native
Aarch64 binaries. If they need to be tested, it is better done using ltp
compiled for 32bit ARM.

Signed-off-by: Riku Voipio <riku.voipio@linaro.org>
Signed-off-by: Mike Frysinger <vapier@gentoo.org>