syscalls/dup203.c: Fix a compiler error
Building dup203 threw the following error:
-----------------------------------------
dup203.c:40:2: error: format string is not a string literal
-----------------------------------------

Fixes: 711f40c09bdb ("syscalls/dup2/dup203: Convert to new API")
Signed-off-by: Xiao Yang <yangx.jy@fujitsu.com>