syscalls/getrusage04: Link rt through LDLIBS instead of LDFLAGS.
Fixes this build error on Ubuntu introduced with commit
07f4e5432dd3e7a60bc0235f13200640c82d8f89.

testcases/kernel/syscalls/getrusage/getrusage04.c:186: undefined reference to `clock_getres'

Signed-off-by: Vinson Lee <vlee@twitter.com>