readlink01: silence coverity error
Coverity found following overrun, which can't really happen.
Presumably because value of exp_val is runtime based, so
coverity assumed that its value can be much higher.

Replace strlen with sizeof to eliminate noise in coverity scans.

Error: OVERRUN (CWE-119):
readlink01.c:109: identity_transfer: Passing "256UL" as argument 3 to function "readlink", which returns that argument. [Note: The source code implementation of the function has been overridden by a builtin model.]
readlink01.c:109: assignment: Assigning: "TEST_RETURN" = "readlink("slink_file", buffer, 256UL)". The value of "TEST_RETURN" is now 256.
readlink01.c:123: cond_const: Checking "TEST_RETURN == exp_val" implies that "exp_val" is 256 on the true branch.
readlink01.c:125: overrun-buffer-arg: Overrunning array ""testfile"" of 9 bytes by passing it to a function which accesses it at byte offset 255 using argument "exp_val" (which evaluates to 256).

Signed-off-by: Jan Stancek <jstancek@redhat.com>