cpuset/cpuset_syscall_test: check HAVE_DECL_MPOL_F_MEMS_ALLOWED
This is to fix compilation on RHEL5.3:
  gcc -g -O2 -g -O2 -fno-strict-aliasing -pipe -Wall -D_FORTIFY_SOURCE=2
  -I/root/ltp/testcases/kernel/include -DNUMA_VERSION1_COMPATIBILITY
  -I../../../../../include -I../../../../../include
  -L/root/ltp/testcases/kernel/controllers/cpuset/cpuset_syscall_test/../cpuset_lib
  -L/root/ltp/testcases/kernel/controllers/cpuset/cpuset_syscall_test/../../libcontrollers
  -L../../../../../lib  cpuset_syscall_test.c   -lltp -lcpu_set
  -lcontrollers -lltp -lnuma -o cpuset_syscall_test
  cpuset_syscall_test.c: In function ‘test_get_mempolicy’:
  cpuset_syscall_test.c:190: error: ‘MPOL_F_MEMS_ALLOWED’ undeclared
  (first use in this function)
  cpuset_syscall_test.c:190: error: (Each undeclared identifier is
  reported only once
  cpuset_syscall_test.c:190: error: for each function it appears in.)
  make[5]: *** [cpuset_syscall_test] Error 1

This patch restores check which has been removed by this commit:
  commit 87156a05a2ffd50f5e467d6f986daae9da7b9cf7
  Author: Stanislav Kholmanskikh <stanislav.kholmanskikh@oracle.com>
  Date:   Tue Oct 1 17:44:50 2013 +0400
    cpuset/cpuset_syscall_test: fixes

Signed-off-by: Jan Stancek <jstancek@redhat.com>
Tested-by: Cyril Hrubis <chrubis@suse.cz>