syscalls/recvmmsg01.c: Fix a compiler error
Use correct ts.type to fix the following compiler error:
--------------------------------------------
recvmmsg01.c:86:9: error: request for member ‘type’ in something not a structure or union
  timeout.type = tv->ts_type;
--------------------------------------------

Fixes: #727
Fixes: 135af8ededd4 ("syscalls/{send|recv}mmsg: add a test case for timeout and errno test")
Reported-by: Li Wang <liwang@redhat.com>
Reported-by: Po-Hsu Lin <po-hsu.lin@canonical.com>
Signed-off-by: Xiao Yang <yangx.jy@cn.fujitsu.com>
Reviewed-by: Petr Vorel <pvorel@suse.cz>
Acked-by: Jan Stancek <jstancek@redhat.com>