ltp: Fix PAGE_SIZE already defined in musl
When ltp building with musl, the following error appears:

|stack_clash.c:50:22: error: expected identifier or '(' before numeric constant
| static unsigned long PAGE_SIZE;

This is because PAGE_SIZE already defined in musl, we can check it here:

    https://git.musl-libc.org/cgit/musl/tree/include/limits.h#n43

So we renamed 'PAGE_SIZE' to 'page_size'

Signed-off-by: Dengke Du <dengke.du@windriver.com>