Add improved checks for mbind(2) syscalls, because...
Hi,

I tried to make with 2010-01-14's cvs in RHEL4.8 (2.6.9-89.ELsmp).
But It failed in "mbind01.c" by following message.

------------
gcc -g -O2 -g -O2 -fno-strict-aliasing -pipe -Wall
-I/home/LTP/ltp-2010-01-12/testcases/kernel/include
-I/home/LTP/ltp-2010-01-12/testcases/kernel/syscalls/mbind/../utils/
-I../../../../include -I../../../../include   -L../../../../lib  mbind01.c
-lltp -lnuma -o mbind01
mbind01.c:184: error: `MPOL_DEFAULT' undeclared here (not in a function)
mbind01.c:184: error: initializer element is not constant
mbind01.c:184: error: (near initialization for `tcase[0].policy')
mbind01.c:188: error: initializer element is not constant
mbind01.c:188: error: (near initialization for `tcase[0]')
mbind01.c:190: error: initializer element is not constant
mbind01.c:190: error: (near initialization for `tcase[1].policy')
mbind01.c:194: error: initializer element is not constant
mbind01.c:194: error: (near initialization for `tcase[1]')
mbind01.c:196: error: `MPOL_BIND' undeclared here (not in a function)
mbind01.c:196: error: initializer element is not constant
mbind01.c:196: error: (near initialization for `tcase[2].policy')
mbind01.c:200: error: initializer element is not constant
mbind01.c:200: error: (near initialization for `tcase[2]')
mbind01.c:202: error: initializer element is not constant
mbind01.c:202: error: (near initialization for `tcase[3].policy')
mbind01.c:206: error: initializer element is not constant
mbind01.c:206: error: (near initialization for `tcase[3]')
mbind01.c:208: error: `MPOL_INTERLEAVE' undeclared here (not in a function)
mbind01.c:208: error: initializer element is not constant
mbind01.c:208: error: (near initialization for `tcase[4].policy')
mbind01.c:212: error: initializer element is not constant
mbind01.c:212: error: (near initialization for `tcase[4]')
mbind01.c:214: error: initializer element is not constant
mbind01.c:214: error: (near initialization for `tcase[5].policy')
mbind01.c:218: error: initializer element is not constant
mbind01.c:218: error: (near initialization for `tcase[5]')
mbind01.c:220: error: `MPOL_PREFERRED' undeclared here (not in a function)
mbind01.c:220: error: initializer element is not constant
mbind01.c:220: error: (near initialization for `tcase[6].policy')
mbind01.c:224: error: initializer element is not constant
mbind01.c:224: error: (near initialization for `tcase[6]')
mbind01.c:226: error: initializer element is not constant
mbind01.c:226: error: (near initialization for `tcase[7].policy')
mbind01.c:230: error: initializer element is not constant
mbind01.c:230: error: (near initialization for `tcase[7]')
mbind01.c:236: error: initializer element is not constant
mbind01.c:236: error: (near initialization for `tcase[8]')
mbind01.c:238: error: initializer element is not constant
mbind01.c:238: error: (near initialization for `tcase[9].policy')
mbind01.c:243: error: initializer element is not constant
mbind01.c:243: error: (near initialization for `tcase[9]')
mbind01.c:246: error: initializer element is not constant
mbind01.c:246: error: (near initialization for `tcase[10].policy')
mbind01.c:250: error: initializer element is not constant
mbind01.c:250: error: (near initialization for `tcase[10]')
mbind01.c: In function `do_test':
mbind01.c:309: error: `MPOL_F_ADDR' undeclared (first use in this function)
mbind01.c:309: error: (Each undeclared identifier is reported only once
mbind01.c:309: error: for each function it appears in.)
make[4]: *** [mbind01] Error 1
------------

Following version's cvs's bring same results.
 - 2010-01-08
 - 2010-01-12
 - 2010-01-13

Signed-off-by: Garrett Cooper <yanegomi@gmail.com>