lapi/io_uring.h: Add __kernel_rwf_t declaration
Kernel commit ddef7ed2b5cb ("annotate RWF_... flags") in 4.14-rc1
added in <linux/fs.h> __kernel_rwf_t data type.

Fix build error on older kernels:

In file included from io_uring01.c:20:
../../../../include/lapi/io_uring.h:38: error: expected specifier-qualifier-list before ‘__kernel_rwf_t’
io_uring01.c:266: warning: missing initializer
io_uring01.c:266: warning: (near initialization for ‘(anonymous)[1].ptr’)
io_uring01.c:268: warning: missing initializer
io_uring01.c:268: warning: (near initialization for ‘test.caps’)
make: *** [io_uring01] Error 1

Fixes: 95399bc87 ("lapi/io_uring: Preparation for io_uring tests")

Signed-off-by: Yang Xu <xuyang2018.jy@cn.fujitsu.com>
Reviewed-by: Petr Vorel <pvorel@suse.cz>
Reviewed-by: Cyril Hrubis <chrubis@suse.cz>