ci/alpine: Fix build error due missing package
Alpine fails because libacl is not installable on 3.21:

apk add acl-dev asciidoc asciidoctor autoconf automake clang gcc git
keyutils-dev libaio-dev libacl libcap-dev libselinux-dev libsepol-dev
libtirpc-dev linux-headers make musl-dev numactl-dev openssl-dev
perl-json pkgconfig
ERROR: unable to select packages:
  libacl (no such package):
    required by: world[libacl]

We actually need also the acl headers, thus install acl-dev,
which contains not only libacl.so, but also the headers and pkg-config
file.

Signed-off-by: Petr Vorel <pvorel@suse.cz>