Fix the missing event.h error found by Tomomori-san on systems without event.h by picking it up from the src directory as described in the following message.
Signed-off-by: Garrett Cooper <yanegomi@gmail.com>

Hi,

I ran "make" with "ltp-2009-12-16" and "ltp-2009-12-18" cvs,
but it failed:
------------
[...]
gcc -g -O2 -g -O2 -fno-strict-aliasing -pipe -Wall  -I../../../include
-I../../../include
 -L../../../lib
-L/home/mitani/LTP/ltp-2009-12-18/testcases/kernel/syscalls/libevent/lib
 libevent/test/regress.c  -levent -o libevent/test/regress
libevent/test/regress.c:44:19: error: event.h: No such file or directory
libevent/test/regress.c: In function 'simple_read_cb':
libevent/test/regress.c:69: warning: implicit declaration of function
'event_add'
libevent/test/regress.c: In function 'multiple_write_cb':
libevent/test/regress.c:100: warning: implicit declaration of function
'event_del'
libevent/test/regress.c: In function 'signal_cb':
libevent/test/regress.c:159: warning: implicit declaration of function
'signal_del'
libevent/test/regress.c: At top level:
libevent/test/regress.c:164: error: field 'ev' has incomplete type
[...]
libevent/test/regress.c:455: warning: implicit declaration of function
'bufferevent_write'
libevent/test/regress.c:459: warning: implicit declaration of function
'bufferevent_free'
libevent/test/regress.c: In function 'main':
libevent/test/regress.c:473: warning: implicit declaration of function
'event_init'
make[3]: *** [libevent/test/regress] Error 1
make[3]: Leaving directory
`/home/mitani/LTP/ltp-2009-12-18/testcases/kernel/syscalls'
make[2]: *** [all] Error 2
[...]
------------

"regress.c" was not compiled before "ltp-2009-12-15" cvs.
It seems to have been compiled after "ltp-2009-12-16" cvs
for the first time.


The results of "make" are various by environment as follows:

 (1) RHEL5.4(2.6.18-164.el5) x86    : succeeded
 (2) RHEL5.4(2.6.18-164.el5) x86_64 : failed
 (3) RHEL5.4(2.6.18-164.el5) ia64   : failed
 (4) RHEL4.8(2.6.9-89.ELsmp) x86    : succeeded

There is "/usr/local/include/event.h" file in the successful system.
There is not "/usr/local/include/event.h" file in the failed system.

"/usr/local/include/event.h" file completely accords with
"${LTPROOT}/testcases/kernel/syscalls/libevent/event.h" file.
I think that "${LTPROOT}/testcases/kernel/syscalls/libevent/event.h"
copied to "/usr/local/include/event.h" when installed.

However, depending on system, there seems to be the case that
this file isn't copied.