dirtyc0w: Include stdint.h
uintptr_t is defined in stdint.h

Fixes
| dirtyc0w_child.c:76:15: error: 'uintptr_t' undeclared (first use in this function); did you mean 'intptr_t'?
|    lseek(mfd, (uintptr_t) map, SEEK_SET);
|                ^~~~~~~~~

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Acked-by: Jan Stancek <jstancek@redhat.com>