rpc: Use libtirpc for all RPC tests + detect headers location
RPC implementation in glibc has been deprecated since glibc 2.16
(headers + bindings were available via --enable-obsolete-rpc) and other
libc ususaly don't implement rpc anyway, it's time to move on and link
against libtirpc. While this fixes problem on these libc
implementations, without libtirpc we obviously end up with no RPC tests.

openSUSE recently moved /usr/include/tirpc to /usr/include as part of
upgrade to glibc 2.27 [1]. Fedora is planning something similar [2].
That's why is needed to detect the correct location and use lapi header.

The reason doing it in one commit is not to break systems using still
/usr/include/tirpc for libtirpc headers:
In file included from ../../../../../../include/lapi/rpc.h:31:0,
                 from librpc01.c:19:
/usr/include/tirpc/rpc/rpc.h:74:10: fatal error: rpc/rpcb_clnt.h: No such file or directory
 #include <rpc/rpcb_clnt.h> /* rpcbind interface functions */

[1] https://build.opensuse.org/package/view_file/Base:System/libtirpc/libtirpc.changes?expand=1
[2] https://bugzilla.redhat.com/show_bug.cgi?id=1537432

Signed-off-by: Petr Vorel <pvorel@suse.cz>
Acked-by: Cyril Hrubis <chrubis@suse.cz>