configure.ac: fix mount_attr detection
Commit b857f8723f30a4b9554bf6b0ff8fa52fd07e8b60 tried to fix build with
latest glibc which provides mount_attr in sys/mount.h. Unfortunately,
the following build failure is still raised because sys/mount is now
unconditionally included in include/lapi/fsmount.h:

In file included from fsconfig01.c:9:
../../../../include/lapi/fsmount.h:55:8: error: redefinition of 'struct mount_attr'
   55 | struct mount_attr {
      |        ^~~~~~~~~~
In file included from ../../../../include/lapi/fsmount.h:14:
/home/autobuild/autobuild/instance-4/output-1/host/armeb-buildroot-linux-gnueabi/sysroot/usr/include/sys/mount.h:210:8: note: originally defined here
  210 | struct mount_attr
      |        ^~~~~~~~~~

Fixes: b857f8723 ("lapi/fsmount: resolve conflict in different header files")
Fixes: http://autobuild.buildroot.org/results/4dbb72e1bf081afd3cd944571b9beeefc7608865
Link: https://lore.kernel.org/ltp/20230226192554.669332-1-fontaine.fabrice@gmail.com/
Reviewed-by: Li Wang <liwang@redhat.com>
[ pvorel: fix from b857f8723 is needed for glibc before glibc-2.37~426,
i.e. without fix 774058d729 ("linux: Fix sys/mount.h usage with kernel headers")
(which was backported to 2.35 and 2.34 maintenance). ]
Reviewed-by: Petr Vorel <pvorel@suse.cz>
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>