realtime/pi-tests: Replace pthread_yield() with	sched_yield()
pthread_yield() is glibc specific. On Linux, it's implemented as a call
to sched_yield(2), which is POSIX.

This fixes build error on musl:
testpi-3.c:142:3: warning: implicit declaration of function ‘pthread_yield’; did you mean ‘pthread_kill’? [-Wimplicit-function-declaration]

Signed-off-by: Petr Vorel <petr.vorel@gmail.com>