Fixed static build which needs to link the pthread library in pidns and pipeio. Signed-off-by: nobuhiro <nobuhiro@andestech.com>. Matt Helsley <matthltc@us.ibm.com> replied: I'm not sure this is correct. I just did a CVS update and grepped for "pthread". I don't see a single use of pthreads in there. What output suggested all of these tests need to link to pthreads? Could you at least stick that in the changelog? Regardless, I'm satisfied with the patch itself. As I said before the changelog would be nicer if it included a snippet of the output that justifies it (included here for convenience): When static linking, the pthread stuff is due to the undefined pthread symbols in librt.a and libgcc_eh.a. make[4]: Entering directory `/home/nobuhiro/git_repo/os/ltp/testcases/kernel/ipc/pipeio' cc -Wall  -static -Wall  -I../../../../include   pipeio.c  -L../../../../lib -lltp -lrt -o pipeio /usr/lib/gcc/x86_64-pc-linux-gnu/4.3.3/../../../../lib64/librt.a(aio_suspend.o): In function `cleanup': (.text+0xa): undefined reference to `pthread_mutex_lock'.