ltp: fix two failures when build with musl
error 1:

|stack_clash.c:50:22: error: expected identifier or '(' before numeric constant
| static unsigned long PAGE_SIZE;

This is because the musl libc already contain PAGE_SIZE definition in limits.c,
we can check it here:

    https://git.musl-libc.org/cgit/musl/tree/include/limits.h#n43

error 2:

|ck01.c:157:22: error: 'O_CREAT' undeclared (first use in this function); did you mean 'S_IREAD'?
|   fd = open(filename, O_CREAT | O_TRUNC | O_RDWR, 0644);
|                       ^~~~~~~
|                       S_IREAD

This is because the musl libc put those in fcntl.h, so we should include that
file.

Signed-off-by: Dengke Du <dengke.du@windriver.com>