lib: Fix undefined reference to `mq_open'
This commit moves the safe_mq_open() function into the header
which fixes undeterministic linker failures.

This fix replaces the reverted commit:

commit fcfb6970002454cfa29cf679a82ba92c94fb59e0
Author: Cyril Hrubis <chrubis@suse.cz>
Date:   Wed Mar 29 18:44:44 2017 +0200

    lib: Fix undefined reference to `mq_open' build failures

Signed-off-by: Cyril Hrubis <chrubis@suse.cz>
Suggested-by: Jan Stancek <jstancek@redhat.com>