Fix _GNU_SOURCES macro requirement error.
It appears that there's a bug in our version of libevent where the requirement that _GNU_SOURCES be set prior to stdio being #include'd for vasprintf(3) wasn't being required until recent versions of glibc:

...
buffer.c: In function ‘evbuffer_add_printf’:
buffer.c:91: warning: implicit declaration of function ‘vasprintf’
buffer.c:95: warning: pointer targets in passing argument 2 of
‘evbuffer_add’ differ in signedness
rm -f libevent.a
ar cru libevent.a event.o buffer.o evbuffer.o select.o poll.o epoll.o
signal.o
ar: -u: (PROGRAM ERROR) Option should have been recognized!?
Try `ar --help' or `ar --usage' for more information.
make[4]: *** [libevent.a] Error 64
make[4]: Leaving directory
`/root/ltp-dev/testcases/kernel/syscalls/libevent'
make[3]: *** [libevent/lib/libevent.a] Error 2
make[3]: Leaving directory `/root/ltp-dev/testcases/kernel/syscalls'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/root/ltp-dev/testcases/kernel'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/root/ltp-dev/testcases'
make: *** [testcases-all] Error 2
mls41:~/ltp-dev # uname -a
Linux mls41 2.6.32.8-0.3-default #1 SMP 2010-02-22 16:22:25 +0100 x86_64
x86_64 x86_64 GNU/Linux
mls41:~/ltp-dev #

So let's fix this nasty issue in a nasty way, see whether or not the problem still exists upstream, resolve there if necessary and sync the new version / change back down here.

Signed-off-by: Garrett Cooper <yanegomi@gmail.com>