Subrata Modak <subrata@linux.vnet.ibm.com> wrote: The tcore_patch_test_suite was added to LTP on Fri Jan 17 22:07:55 2003 UTC, with contribution from you. As i try to compile it today, i get the following error: [tcore_patch_test_suites]$ make  gcc  -o tcore tcore.c -lm -lpthread  tcore.c: In function ‘producer’:  tcore.c:129: error: memory input 0 is not directly addressable  tcore.c: In function ‘consumer’:  tcore.c:166: error: memory input 0 is not directly addressable  tcore.c:167: error: memory input 0 is not directly addressable  make: *** [tcore] Error 1 Can you please let me know:  1) Any fix for this Failure ?  2) Relevance of this test case today, whether they need to be there in  LTP or not ?
Gowrishankar <gomuthuk@linux.vnet.ibm.com> replied:
I have made it to compile and run with below patch. Using proper extended asm stops this problem. Below patch uses gcc's extended asm instead of basic inlines on this test which stops compilation problem with newer gcc's (v4). Signed-off-by: Gowrishankar M <gowrishankar.m@linux.vnet.ibm.com>.