tirpc: Require libtirpc >= 0.2.4
Libtirpc 0.2.3 contains a bug introduced in 8271dfe ("Reference count AUTHs"):

testcases/network/rpc/rpc-tirpc/tests_pack/rpc_suite/rpc/rpc_auth_auth_destroy/rpc_auth_destroy.c:53: error: implicit declaration of function 'log_debug'
make[8]: *** [rpc_auth_destroy] Error 1

This bug was also backported to some other versions (i.e.
libtirpc-devel-0.2.1-15.el6 in CentOS 6). Instead fixing code for this
old version (2013) just require 0.2.4, which contains a fix 9ce88a3
("Remove variadic macro invocation").

Fixes: c7d2a7458 ("rpc-tirpc: Detect libtirpc with pkg-config")

Signed-off-by: Petr Vorel <pvorel@suse.cz>