device-drivers/acpi/ltp_acpi_cmds: Fix build errors
There exist the following errors when building LTP on the
latest Linux kernel v6.16-rc6:

  ltp_acpi_cmds.c:39:10: fatal error: linux/genhd.h: No such file or directory
  ltp_acpi_cmds.c:131:18: error: implicit declaration of function 'acpi_bus_get_device'
  ltp_acpi_cmds.c:400:18: error: implicit declaration of function 'acpi_bus_get_device'

For the first error:

This is because genhd.h has been removed in the Linux kernel,
the contents of genhd.h was folded into blkdev.h [1].

Add linux/genhd.h into AC_CHECK_HEADERS_ONCE of configure.ac,
define HAVE_LINUX_GENHD_H to 1 if you have the <linux/genhd.h>
header file, then use #ifdef HAVE_LINUX_GENHD_H to include it.

For the second and third errors:

This is because acpi_bus_get_device() has been removed in the
Linux kernel [2] since v5.18-rc2 [3], the best way is to use
acpi_bus_get_device() if the kernel version < 5.18 and use
acpi_fetch_acpi_dev() if the kernel version >= 5.18.

While at it, remove the trailing whitespace in the following
code: prk_alert("TEST -- acpi_bus_update_power ").

Link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=322cbb50de71 [1]
Link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=ac2a3feefad5 [2]
Link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/log/?h=v5.18-rc2 [3]

Link: https://lore.kernel.org/ltp/20250718082935.9466-1-yangtiezhu@loongson.cn/
Suggested-by: Andrea Cervesato <andrea.cervesato@suse.com>
Suggested-by: Petr Vorel <pvorel@suse.cz>
Reviewed-by: Petr Vorel <pvorel@suse.cz>
Signed-off-by: Tiezhu Yang <yangtiezhu@loongson.cn>