lib/tst_kvercmp: fixed a compiling error
commit 18f7be7eb introduced the following compiling error:

make[1]: Leaving directory `/mnt/tests/kernel/distribution/ltp/git_test/ltp/testcases/kernel/containers/libclone'
gcc -g -O2 -g -O2 -fno-strict-aliasing -pipe -Wall  -I../../../include -I../../../include   -L../../../lib  check_for_unshare.c  -ldl -lltp -o check_for_unshare
check_for_unshare.c: In function ‘main’:
check_for_unshare.c:35:8: warning: variable ‘ret’ set but not used [-Wunused-but-set-variable]
  void *ret;
        ^
../../../lib/libltp.a(tst_res.o): In function `cat_file':
/mnt/tests/kernel/distribution/ltp/git_test/ltp/lib/tst_res.c:777: undefined reference to `TCID'
/mnt/tests/kernel/distribution/ltp/git_test/ltp/lib/tst_res.c:787: undefined reference to `TCID'
/mnt/tests/kernel/distribution/ltp/git_test/ltp/lib/tst_res.c:795: undefined reference to `TCID'
../../../lib/libltp.a(tst_res.o): In function `tst_res':
/mnt/tests/kernel/distribution/ltp/git_test/ltp/lib/tst_res.c:301: undefined reference to `TCID'
/mnt/tests/kernel/distribution/ltp/git_test/ltp/lib/tst_res.c:317: undefined reference to `TCID'
../../../lib/libltp.a(tst_res.o):/mnt/tests/kernel/distribution/ltp/git_test/ltp/lib/tst_res.c:370: more undefined references to `TCID' follow
collect2: error: ld returned 1 exit status
make: *** [check_for_unshare] Error 1

that's because commit 18f7be7eb used LTP lib function tst_resm(), using printf() instead can avoid it.

Signed-off-by: Zhouping Liu <zliu@redhat.com>
Reviewed-by: Wanlong Gao <gaowanlong@cn.fujitsu.com>