tst_af_alg: fix build when ALG_SET_AEAD_ASSOCLEN undefined
On older kernel such as 3.10.0-1136.el7.x86_64, compile failed as below:
tst_af_alg.c: In function ‘tst_alg_sendmsg’:
tst_af_alg.c:205:21: error: ‘ALG_SET_AEAD_ASSOCLEN’ undeclared (first use in this function)
   cmsg->cmsg_type = ALG_SET_AEAD_ASSOCLEN;
                     ^
tst_af_alg.c:205:21: note: each undeclared identifier is reported only once for each function it appears in
make: *** [tst_af_alg.o] Error 1

Add check for struct af_alg_iv and struct sockaddr_alg.

The ALG_SET_AEAD_ASSOCLEN flag was introduced since kernel commit af8e80731a
("crypto: af_alg - add user space interface for AEAD") in 2014.

Fixes: 3cbb963abb ("lib/tst_af_alg: add tst_alg_sendmsg()")
Signed-off-by: Yang Xu <xuyang2018.jy@cn.fujitsu.com>
Reviewed-by: Petr Vorel <pvorel@suse.cz>