lapi: Add posix_types.h
To fix undefined __kernel_ulong_t, which was defined in v3.4-rc1
in afead38d011a ("posix_types: Introduce __kernel_[u]long_t").

This fixed build error:

In file included from /usr/src/ltp/include/lapi/msgbuf.h:13,
                 from /usr/src/ltp/testcases/kernel/syscalls/ipc/msgctl/msgctl05.c:9:
/usr/src/ltp/include/lapi/ipcbuf.h: At top level:
/usr/src/ltp/include/lapi/ipcbuf.h:187: error: expected specifier-qualifier-list before '__kernel_ulong_t'

Fixes: 3e1fc0644 ("include: Add declaration of struct ipc64_perm")

Reviewed-by: Cyril Hrubis <chrubis@suse.cz>
Reviewed-by: Viresh Kumar <viresh.kumar@linaro.org>
Signed-off-by: Petr Vorel <pvorel@suse.cz>