sched_stress: Use time_t instead of long for type
This fixes warnings on musl:

| sched_driver.c:744:43: error: passing argument 1 of 'ctime' from incompatible pointer type [-Wincompatible-pointer-types]
|   744 |         printf("\nend time = %s\n", ctime(&end_time));
|       |                                           ^~~~~~~~~

Link: https://lore.kernel.org/ltp/20240506190348.1448707-1-raj.khem@gmail.com/
Reviewed-by: Petr Vorel <pvorel@suse.cz>
Signed-off-by: Khem Raj <raj.khem@gmail.com>