libcpuset.c: fix error of undefined reference to 'get_mempolicy'
'HAVE_DECL_MEMPOLICY' is wrong in commit 6c4d1c6.

Signed-off-by: Peng Haitao <penght@cn.fujitsu.com>