getcontext01: fix build using uClibc C runtime
Fix a build error when __UCLIBC__ is defined (see log below)
by moving all headers inclusion and TCID definition on top of file
as they are required by 'tst_brkm' function too.

getcontext01.c: In function ‘main’:
getcontext01.c:103:2: warning: implicit declaration of function ‘tst_brkm’
getcontext01.c:103:11: error: ‘TCONF’ undeclared (first use in this function)
getcontext01.c:103:11: note: each undeclared identifier is reported only once for each function it appears in
getcontext01.c:103:18: error: ‘NULL’ undeclared (first use in this function)
getcontext01.c:104:1: warning: control reaches end of non-void function

Signed-off-by: Francesco Rundo <francesco.rundo@st.com>
Signed-off-by: Carmelo Amoroso <carmelo.amoroso@st.com>
Acked-by: Mike Frysinger <vapier@gentoo.org>