setgid03.c: fix build
This patch fixes build errors introduced with commit
7dc42c97696f135e1fef92e612ecc66bf8d74318.

setgid03.c:36:23: error: static declaration of ‘getpwnam’ follows non-static declaration
In file included from setgid03.c:24:0:
/usr/include/pwd.h:117:23: note: previous declaration of ‘getpwnam’ was here
setgid03.c:39:1: error: duplicate ‘static’
setgid03.c:40:1: error: duplicate ‘static’

Signed-off-by: Vinson Lee <vlee@twitter.com>
Signed-off-by: Zhouping Liu <zliu@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>