Fix missing `_' in constant name.
I tried to build open_posix_testsuite testcases with latest git:
  ltp-dev-7c67a09a10268b5f9f503e0254f1f0f9f5ac2b69.tar.gz

Several testcases failed to build.
One of them is as follows:
------------
[...]
conformance/definitions/sched_h/8-3-buildonly compile FAILED
../../../conformance/definitions/sched_h/8-3-buildonly.c:24:2: error:
 #error
SCHED_SPORADIC not defined
[...]
------------

I noticed that "POSIX_THREAD_SPORADIC_SERVER" parameter has not "_"
in its top.

Signed-off-by: Tomonori Mitani <mitani@ryobi.co.jp>
Acked-by: Garrett Cooper <yanegomi@gmail.com>