mount/mount03.c: Add mode argument to open call.
This patch fixes this build error on Ubuntu introduced with commit
24324ad5dae71172125060b82580486b0f3d37da.

In file included from /usr/include/fcntl.h:252:0,
                 from mount03.c:73:
In function ‘open’,
    inlined from ‘setup’ at mount03.c:447:5:
/usr/include/x86_64-linux-gnu/bits/fcntl2.h:51:24: error: call to ‘__open_missing_mode’ declared with attribute error: open with O_CREAT in second argument needs 3 arguments

Signed-off-by: Vinson Lee <vlee@twitter.com>
Signed-off-by: Wanlong Gao <gaowanlong@cn.fujitsu.com>