rpc/rpc-tirpc: Fix compile error on clang when using clnt_broadcast
When clang upgrade to 16.0.0-2.fc38, these case will report
incompatible-function-pointer-types  error as below:

rpc_clnt_broadcast_complex.c:81:46: error: incompatible function pointer types passing
'bool_t (char *, struct sockaddr_in *)' (aka 'int (char *, struct sockaddr_in *)') to
parameter of type 'resultproc_t' (aka 'int (*)(char *, ...)') [-Wincompatible-function-pointer-types]
(xdrproc_t) xdr_int, (char *)&varRec, eachResult);

the clnt_broadcase declare as below:
extern enum clnt_stat   clnt_broadcast(u_long, u_long, u_long,
                                         xdrproc_t, void *,
                                         xdrproc_t, void *,
                                         resultproc_t);

so we should add resultproc_t cast like tirpc_simple_rpc_broadcast.c[1]
call rpc_broadcast() does.

[1]https://github.com/linux-test-project/ltp/blob/master/testcases/network/rpc/rpc-tirpc/tests_pack/rpc_suite/tirpc/tirpc_simple_rpc_broadcast/tirpc_rpc_broadcast_complex.c

Reviewed-by: Petr Vorel <pvorel@suse.cz>
Signed-off-by: Yang Xu <xuyang2018.jy@fujitsu.com>