move_pages12: Fix undefined reference to WIFEXITED()
The test failed to compile on slightly older glibc due to missing
reference to WIFEXITED() caused by missing <sys/wait.h> include.

Signed-off-by: Cyril Hrubis <chrubis@suse.cz>