profile01: fix build using uClibc runtime
Fix a build error when __UCLIBC__ is defined (see log below)
by moving all headers inclusion and TCID definition on top of file
as they are required by 'tst_brkm' function too.

profil01.c: In function ‘main’:
profil01.c:311:2: warning: implicit declaration of function ‘tst_exit’
profil01.c:312:1: warning: control reaches end of non-void function
 ../../../../lib/libltp.a(tst_res.o): In function `cat_file':
/stlinux/amorosoc/git/stm/ltp/lib/tst_res.c:733: undefined reference to `TCID'
../../../../lib/libltp.a(tst_res.o): In function `tst_res':
/stlinux/amorosoc/git/stm/ltp/lib/tst_res.c:300: undefined reference to `TCID'
/stlinux/amorosoc/git/stm/ltp/lib/tst_res.c:284: undefined reference to `TCID'
/stlinux/amorosoc/git/stm/ltp/lib/tst_res.c:323: undefined reference to `TCID'
../../../../lib/libltp.a(tst_res.o): In function `tst_brk':
/stlinux/amorosoc/git/stm/ltp/lib/tst_res.c:634: undefined reference to `TCID'
collect2: ld returned 1 exit status

Signed-off-by: Francesco Rundo <francesco.rundo@st.com>
Signed-off-by: Carmelo Amoroso <carmelo.amoroso@st.com>
Acked-by: Mike Frysinger <vapier@gentoo.org>