Applied patch from Mike Frysinger: currently when i try to build test_1_to_1_sockopt.c, it warns about implicit declaration's of htonl/htons: test_1_to_1_sockopt.c: In function `main': test_1_to_1_sockopt.c:201: warning: implicit declaration of function `htonl' test_1_to_1_sockopt.c:202: warning: implicit declaration of function `htons'
this is because these functions are in netinet/in.h but this file includes
linux/in.h and linux/in6.h ... any reason the code just uses netinet/in.h and
drops the linux/in.h and linux/in6.h ?  a quick test against uClibc and glibc
shows that it compiles just fine and doesnt issue any warnings now ...
-mike