mount/mount05.c: Add mode argument to open call.
This patch fixes this build error on Ubuntu introduced with commit
9146d83d410dc060124344fcbcdbf46280b674a2.

In file included from /usr/include/fcntl.h:279:0,
                 from mount05.c:31:
In function ‘open’,
    inlined from ‘main’ at mount05.c:94:12:
/usr/include/x86_64-linux-gnu/bits/fcntl2.h:50:24: error: call to ‘__open_missing_mode’ declared with attribute error: open with O_CREAT in second argument needs 3 arguments

Signed-off-by: Vinson Lee <vlee@twitter.com>
Signed-off-by: Wanlong Gao <gaowanlong@cn.fujitsu.com>