network/vxlan02.sh: Fix duplicate parameters
vxlan02 and vxlan02_ipv6 tests had duplicate parameters 'dev ltp_ns_veth2':
ip li add ltp_v0 type vxlan dstport 0 id 16700000 group 239.1.1.1 dev ltp_ns_veth2 dev ltp_ns_veth2
Error: either "dev" is duplicate, or "ltp_ns_veth2" is a garbage.

Device was specified in in both the test file itself and in virt_add()
function in virt_lib.sh. Removed in test to be consistent with vlan02.sh.

Fixes: 8e5862c20 ("net: vxlan02: specify interface when adding multicast dst")

Signed-off-by: Petr Vorel <pvorel@suse.cz>
Acked-by: Alexey Kodanev <alexey.kodanev@oracle.com>