Fix for missing CAP_SYS_TIME in ltp - ./include/lapi/capability.h
ltp build failed at this point

....
< .downsized output >
..
gcc -g -O2 -g -O2 -fno-strict-aliasing -pipe -Wall -W -Wold-style-definition -D_FORTIFY_SOURCE=2
-I../../../../include -I../../../../include -I../../../../include/old/   -L../../../../lib  settimeofday02.c   -lltp -o settimeofday02
In file included from settimeofday02.c:11:
settimeofday02.c:67:25: error: ‘CAP_SYS_TIME’ undeclared here (not in a function); did you mean ‘CAP_SYS_ADMIN’?
   TST_CAP(TST_CAP_DROP, CAP_SYS_TIME),
                         ^~~~~~~~~~~~
../../../../include/tst_capability.h:21:46: note: in definition of macro ‘TST_CAP’
 #define TST_CAP(action, capability) {action, capability, #capability}
                                              ^~~~~~~~~~
settimeofday02.c:70:1: warning: missing initializer for field ‘test_all’ of ‘struct tst_test’ [-Wmissing-field-initializers]
 };
 ^
In file included from settimeofday02.c:12:
../../../../include/tst_test.h:202:9: note: ‘test_all’ declared here
  void (*test_all)(void);
         ^~~~~~~~
make[4]: *** [<builtin>: settimeofday02] Error 1
make[4]: Leaving directory '/home/ronald/ltp/testcases/kernel/syscalls/settimeofday'
make[3]: *** [../../../include/mk/generic_trunk_target.inc:93: all] Error 2
make[3]: Leaving directory '/home/ronald/ltp/testcases/kernel/syscalls'
make[2]: *** [../../include/mk/generic_trunk_target.inc:93: all] Error 2
make[2]: Leaving directory '/home/ronald/ltp/testcases/kernel'
make[1]: *** [../include/mk/generic_trunk_target.inc:93: all] Error 2
make[1]: Leaving directory '/home/ronald/ltp/testcases'
make: *** [Makefile:108: testcases-all] Error 2
[root@vm37-224 ltp]#
-----------------------

== After applying the fix build succeeded as shown below

< … >
make[4]: Leaving directory '/home/ronald/ltp/testcases/kernel/syscalls/wait4'
make[4]: Entering directory '/home/ronald/ltp/testcases/kernel/syscalls/settimeofday'
install -m 00775 "/home/ronald/ltp/testcases/kernel/syscalls/settimeofday/settimeofday01" "/opt/ltp/testcases/bin/settimeofday01"
install -m 00775 "/home/ronald/ltp/testcases/kernel/syscalls/settimeofday/settimeofday02" "/opt/ltp/testcases/bin/settimeofday02"
make[4]: Leaving directory '/home/ronald/ltp/testcases/kernel/syscalls/settimeofday'
make[4]: Entering directory '/home/ronald/ltp/testcases/kernel/syscalls/sched_get_priority_min'
install -m 00775 "/home/ronald/ltp/testcases/kernel/syscalls/sched_get_priority_min/sched_get_priority_min01" "/opt/ltp/testcases/bin/sched_get_priority_min01"
install -m 00775 "/home/ronald/ltp/testcases/kernel/syscalls/sched_get_priority_min/sched_get_priority_min02" "/opt/ltp/testcases/bin/sched_get_priority_min02"
make[4]: Leaving directory '/home/ronald/ltp/testcases/kernel/syscalls/sched_get_priority_min'
 < .. >

Signed-off-by: Ronald Monthero <rmonther@redhat.com>