syscalls/sendmmsg: Fix build error on old systems
Old systems which don't have sendmmsg() must keep return value:
sendmmsg_var.h:20: error: no return statement in function returning non-void

Fixes: a8546e550 ("syscalls/sendmmsg: Add support for time64 tests")

Signed-off-by: Petr Vorel <pvorel@suse.cz>