Modified nets/Makefile for appending one file which needs in /opt/ltp/tetscases/bin directory while install.
=======================================================================================
parentns.sh    0  TINFO  :  Pinging ChildNS from ParentNS
sshd re-exec requires execution with an absolute path
/opt/ltp/testcases/bin/ch_ftp.sh: line 37: ./container_ftp.pl: No such file or directory
childns.sh    1  TFAIL  :  ftp failed
Error while running the script
two_children_ns: return code is 1 ; par_chld_ftp: FAIL 1 ;
=======================================================================================

After patch applied the resule is like this:

=======================================================================================
parentns.sh    0  TINFO  :  Pinging ChildNS from ParentNS
sshd re-exec requires execution with an absolute path
Error: Can't ftp to 192.168.0.181: Connection refused
childns.sh    1  TFAIL  :  ftp failed
Error while running the script
two_children_ns: return code is 1 ; par_chld_ftp: FAIL 1 ;
=======================================================================================

Signed-off-by: Rishikesh K Rajak <risrajak@linux.vnet.ibm.com>