syscalls/ioctl07.c: Fix compilation && Cleanup
1) Fix compilation error on older kernels(e.g RHEL5.11GA) due to
   undefined __u32, as below:
   error: expected specifier-qualifier-list before ‘__u32’
   error: expected specifier-qualifier-list before ‘__u32’

2) Remove unused tst_safe_stdio.h header file

Signed-off-by: Xiao Yang <yangx.jy@cn.fujitsu.com>