ci: Skip openSUSE builds on broken repositories
opensuse/leap:latest container repos are sometimes broken:

zypper --non-interactive install --force-resolution --no-recommends autoconf ...
...
(86/88) Installing: kernel-default-devel-6.4.0-150600.23.47.2.x86_64 [..............done]
(87/88) Installing: libopenssl-devel-3.1.4-150600.2.1.noarch [..done]
(88/88) Installing: clang-17-bp156.1.1.x86_64 [..done]
Error: Process completed with exit code 106.

Previous commit added an attempt to recover from it (which may help) but
this way we get permanent failure in Patchwork (Patchwork API does not
update results, it just adds a new result) it's better to not keep this
as a failure.

Because patchwork does not have state "skip" use state "pending" (quite
correct - not yet tested).

TODO: automatically restart jobs with "pending" state.

Link:https://lore.kernel.org/ltp/20250425153046.63853-5-pvorel@suse.cz/
Acked-by: Andrea Cervesato <andrea.cervesato@suse.com>
Reviewed-by: Li Wang <liwang@redhat.com>
Signed-off-by: Petr Vorel <pvorel@suse.cz>