safe_macros: Include errno.h.
Fix build regression introduced by commit
d6a1f25137b0ac8704bd08cc4bc8af01cceaca0e.

This patch fixes this build error on Ubuntu 11.10.
safe_macros.c: In function ‘safe_strtol’:
safe_macros.c:349:2: error: ‘errno’ undeclared (first use in this
function)
safe_macros.c:349:2: note: each undeclared identifier is reported only
once for each function it appears in
safe_macros.c:351:16: error: ‘ERANGE’ undeclared (first use in this
function)

Signed-off-by: Vinson Lee <vlee@twitter.com>
Acked-by: Wanlong Gao <gaowanlong@cn.fujitsu.com>