pec: Replace obsoleted SA_ONESHOT with SA_RESETHAND
This is needed especially for musl, for glibc _GNU_SOURCE
is added by libc-features.h automatically. which defines SA_ONESHOT

Fixes

pec_listener.c: In function ‘main’:
pec_listener.c:233:27: error: ‘SA_ONESHOT’ undeclared (first use in this function)
  sigint_action.sa_flags = SA_ONESHOT;
                           ^~~~~~~~~~

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Acked-by: Cyril Hrubis <chrubis@suse.cz>