configure.ac: Add _GNU_SOURCE for struct fs_quota_statv check
These changes help ensure that the necessary features and definitions
are available during the configuration process, preventing potential
issues related to missing or incompatible definitions. This should
resolve the compilation error related to struct fs_quota_statv:

 /usr/include/xfs/xqm.h:167:8: error: redefinition of ‘struct fs_qfilestatv’

[ pvorel: This is a workaround for xfsprogs issue, can be removed once
change widely adopted
https://lore.kernel.org/linux-xfs/be7f0845-5d5f-4af5-9ca9-3e4370b47d97@sandeen.net/
]

Link: https://lore.kernel.org/ltp/20240617053436.301336-1-liwang@redhat.com/
Reviewed-by: Petr Vorel <pvorel@suse.cz>
Signed-off-by: Li Wang <liwang@redhat.com>