filecaps: Fix build.
Fix build error that was introduced at commit
66ad27e08d774c572e99e97cc9b885295ec0aa55.

gcc -g -O2 -g -O2 -fno-strict-aliasing -pipe -Wall
-I/tmp/ltp/testcases/kernel/include -D_GNU_SOURCE -I../../../../include
-I../../../../include -L../../../../lib c.c -lltp -o c c.c:22:28: fatal
error: sys/capability.h: No such file or directory

Signed-off-by: Vinson Lee <vlee@twitter.com>
Signed-off-by: Wanlong Gao <gaowanlong@cn.fujitsu.com>