bpf: Fix compilation on old distros
Fixes failure on old distros which use gcc 4.x:

gcc -g -O2 -g -O2 -fno-strict-aliasing -pipe -Wall -W -Wold-style-definition -D_GNU_SOURCE -D_FORTIFY_SOURCE=2 -I../../../../include -I../../../../include -I../../../../include/old/   -L../../../../lib  bpf_map01.c bpf_common.o   -lltp -o bpf_map01
testcases/kernel/syscalls/bpf/../../../../include/lapi/bpf.h:557: multiple definition of `ptr_to_u64'
/tmp/cckcGS9G.o:testcases/kernel/syscalls/bpf/../../../../include/lapi/bpf.h:557: first defined here
bpf_common.o: In function `bpf':
testcases/kernel/syscalls/bpf/../../../../include/lapi/bpf.h:562: multiple definition of `bpf'
/tmp/cckcGS9G.o:testcases/kernel/syscalls/bpf/../../../../include/lapi/bpf.h:562: first defined here
collect2: ld returned 1 exit status
make: *** [bpf_map01] Error 1

Fixes: 71388f3e4 ("Split off executable code from bpf/bpf_common.h")

Signed-off-by: Petr Vorel <pvorel@suse.cz>